using Connector.CcvShop.Api.Base;
using System;

// This file is generated by the Converttool in the solution Connector.CcvShop.
namespace Connector.CcvShop.Api.Webshops
{
    public class WebshopResult : ResultBase
    {
        /// <summary>
        /// <summary>
        /// Unique id of the resource.
        /// Minimum: 0
        /// </summary>
        public int id { get; set; }

        /// <summary>
        /// <summary>
        /// The webshop name.
        /// </summary>
        public string name { get; set; }

        /// <summary>
        /// <summary>
        /// Indicates if this is a webshop or a multishop system. Multiple webshops can be connected to one multishop system.
        /// </summary>
        public bool? is_multishop_system { get; set; }

        /// <summary>
        /// <summary>
        /// The root of the API for this webshop. Do note: other credentials will be needed to access this API.
        /// </summary>
        public Uri api_root { get; set; }

    }
}
